services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend # live kod z hosta
      - ./frontend:/var/www/frontend # live kod z hosta
    ports:
      - "8080:80"
    restart: unless-stopped
