@echo off
echo Uruchamianie backendu PHP...
cd backend
echo Sprawdzanie czy composer install został wykonany...
if not exist "vendor" (
    echo Instalowanie zależności Composer...
    composer install
)
echo Uruchamianie serwera PHP na localhost:8000...
echo Backend będzie dostępny pod: http://localhost:8000
echo Aby zatrzymać serwer, naciśnij Ctrl+C
php -S localhost:8000 -t public