# Nazwa całego procesu
name: Build and Deploy Portfolio to Azure App Service

# Wyzwalacze - kiedy ma się uruchomić
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Definicja zadań do wykonania
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Krok 1: Pobranie kodu z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # Krok 2: Konfiguracja Node.js do budowy frontendu
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' 

    # Krok 3: Budowanie aplikacji Vue.js
    - name: Build Frontend
      run: |
        echo "Building frontend application..."
        npm install
        npm run build
      working-directory: ./frontend
    
    # Krok 4: Instalacja zależności backendu PHP (opcjonalnie, ale dobra praktyka)
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-dev
      working-directory: ./backend

    # Krok 5: Wdrożenie całej aplikacji (z zbudowanym frontendem) na Azure
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'portfolio-php-mariusz'
        # Ten sekret został automatycznie dodany przez Azure - GitHub go znajdzie
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TwojUnikalnyHash }}
        package: .
