name: Build and Deploy Portfolio to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Prepare deployment package
        run: |
          cp -r frontend/dist/* deploy_package/public/
      - name: Install Composer Dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Set execute permission for startup script
        run: chmod +x ./startup.sh

      - name: Prepare deployment package
        run: |
          mkdir deploy_package
          cp -r backend/* deploy_package/
          cp -r frontend/dist/* deploy_package/public/
          cp nginx.conf deploy_package/
          cp startup.sh deploy_package/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'portfolio-php-mariusz'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy_package
